name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10' ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            .bruce/
            .venv/
          key: ${{ runner.os }}-bruce
      - name: "Setup Python: ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Test
        run: ./bruce.py ci
