name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            .bruce/
            .venv/
          key: ${{ runner.os }}-bruce

      - name: Test
        run: ./bruce.py test
